# Generated by Django 4.0.3 on 2022-05-03 10:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vote', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='topic',
            old_name='maket',
            new_name='maker',
        ),
    ]
